# Generated by Django 4.1.6 on 2023-03-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Farm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pquality',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
