# Generated by Django 4.1.6 on 2023-03-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Farm', '0004_alter_product_pquality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pquality',
            field=models.CharField(default='', max_length=10),
        ),
    ]
