# Generated by Django 4.1.6 on 2023-03-25 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Farm', '0005_alter_product_pquality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pquality',
        ),
    ]
