# Generated by Django 4.1.6 on 2023-03-25 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Farm', '0006_remove_product_pquality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
