# Generated by Django 4.1.6 on 2023-03-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Farm', '0007_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=200)),
                ('pprice', models.IntegerField()),
                ('pquantity', models.IntegerField()),
                ('pimage', models.ImageField(default='', upload_to='static/meadia/pimage')),
            ],
        ),
    ]
